### ISSUE TITLE
AMQP报错了，不知道什么原因

### ISSUE THREAD

**Issue by yudexiaobuwuqu** [hyperf/amqp#16]
bash-5.0# php bin/hyperf.php start
PHP Fatal error:  Declaration of Hyperf\Amqp\AMQPConnection::wait_channel($channel_id, $timeout = 0) must be compatible with PhpAmqpLib\Connection\AbstractConnection::wait_channel(int $channel_id, $timeout = 0): PhpAmqpLib\Channel\Frame in /data/project/telegram/vendor/hyperf/amqp/src/AMQPConnection.php on line 288

**Comment by limingxinleo** [comment]
composer require "php-amqplib/php-amqplib:3.4.0" -W
